### ISSUE TITLE
Pre-cast on switch

### ISSUE THREAD

**Issue by Nephryde** [kolton/d2bot-with-kolbot#640] opened 2018-08-23 21:24 UTC
Hello,
is there a possibility to set an energy shield pre-cast on switch but not in CTA? For example, when I have 'Memory' as a switch weapon.
Thank you for any help.

**Comment by mf022** [comment] 2018-08-24 14:07
SVN Update your d2bs folder
https://github.com/kolton/d2bot-with-kolbot/pull/443 was merged few days ago and it's  working as intended.

the case it won't look to the better slot for casting ES will be in the middle of the battle.

**Closed** 2018-09-14 23:37 UTC
